version: '3.4'
services:
  client:
    container_name: cmhfoodinfo_client
    stdin_open: true
    build: 
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - 3000:3000

  server:
    container_name: cmhfoodinfo_server
    stdin_open: true
    build: 
      context: ./server
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql


volumes:
  db:
    driver: local